repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
      language: python
      types: [python]
      args: ["--line-length=120"]
  - repo: https://github.com/pycqa/pylint
    rev: v2.14.3
    hooks:
      - id: pylint